---

- name: schroot
  command: schroot -e -f -c {{ chroot_name }}

- name: stop schroot
  service:
    name: schroot
    state: stopped
  become: yes

- name: Remove directory {{ chroot_dir }}
  file:
    path: "{{ chroot_dir }}"
    state: absent
  become: yes



